# Generated by Django 5.0.7 on 2024-07-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Rider', 'Rider'), ('Driver', 'Driver')], max_length=50),
        ),
    ]
