# Generated by Django 5.0.7 on 2024-07-12 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_rideevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('en-route', 'en-route'), ('pickup', 'pickup'), ('dropoff', 'dropoff')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rideevent',
            name='id_ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rideevent_set', to='rides.ride'),
        ),
    ]
