# Generated by Django 5.0.7 on 2024-07-12 02:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_alter_ride_status_alter_rideevent_id_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='dropoff_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
